---
- hosts: raditz
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    capsulecorp_domain_hostname: "raditz"
    ethernet_adapter: "Ethernet"
    anpt_flag: "flag3.txt"
  tasks:
  - name: Activate windows
    win_shell: cscript slmgr.vbs /rearm
    args:
      chdir: C:\Windows\System32\
  roles:
   - role: joindomain
   - role: placeflag
