---
# Load up the vars file
- name: Include variables
  include_vars: "jenkins.yml"

# Setup/Install tasks.
- include: install_packages.yml

# Configure Jenkins init settings.
- include: settings.yml
  when: jenkins_install_package_win.changed

# Make sure Jenkins starts and configures
- name: Ensure Jenkins starts, then configure Jenkins.
  win_service: name=jenkins state=started start_mode=auto
  when: jenkins_install_package_win.changed

- name: Get the jenkins-cli jarfile from the Jenkins server.
  win_get_url:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  when: jenkins_install_package_win.changed

# Update Jenkins and install configured plugins.
- include: plugins.yml
  when: jenkins_install_package_win.changed

#and finaly restart jenkins
- name: Ensure Jenkins is re-started.
  win_service: name=jenkins state=restarted start_mode=auto
  when: jenkins_install_package_win.changed
